[package]
name = "delta-kernel"
version = "0.0.0"
edition = "2021"
authors = ["Zach Schuermann <zach@zvs.io>"]

[dependencies]
tracing = "0.1" # only for structured logging
# todo depend only on the bits we need (arrow-schema, etc.)
arrow = { version = "^40.0", features = [ "json", "prettyprint" ]}
parquet = "^40.0" # need to generalize over arrow, arrow2 and diff parquet etc. (BYOP)
bytes = "1.4" # HACK only using this since ParquetRecordBatchReaderBuilder requires ChunkRead

# required to deserialize DVs
z85 = "3.0.5"
uuid = "1.3.0"
roaring = "0.10.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }
test-log = { version = "0.2", default-features = false, features = ["trace"] }
