[package]
name = "deltakernel"
version = "0.0.0"
edition = "2021"
build = "build.rs"
authors = [
  "Zach Schuermann <zach@zvs.io>",
  "R. Tyler Croy <rtyler@brokenco.de>",
]
readme = "README.md"
keywords = ["deltalake", "delta", "datalake"]
license = "Apache-2.0"
homepage = "https://delta.io"
repository = "https://github.com/delta-incubator/delta-kernel-rs"

[dependencies]
arrow-array = { version = "^42.0" }
arrow-arith = { version = "^42.0" }
arrow-json = { version = "^42.0" }
arrow-ord = { version = "^42.0" }
arrow-schema = { version = "^42.0" }
arrow-select = { version = "^42.0" }
async-trait = "0.1"
bytes = "1.4"
chrono = { version = "0.4", optional = true }
either = "1.8"
fix-hidden-lifetime-bug = "0.2"
futures = "0.3"
itertools = "0.10"
lazy_static = "1.4"
# used for providing a storage abstraction layer
object_store = "^0.6.0"
# need to generalize over arrow, arrow2 and diff parquet etc. (BYOP)
parquet = "^42.0"
regex = "1.8"
roaring = "0.10.1"
serde = "1"
serde_json = "1"
thiserror = "1"
# only for structured logging
tracing = "0.1"
url = "2"
uuid = "1.3.0"
z85 = "3.0.5"

[features]
default = ["default-client"]
default-client = ["chrono", "parquet/async", "parquet/object_store"]

[build-dependencies]
ureq = "2.2.0"
flate2 = "1.0.20"
tar = "0.4.36"

[dev-dependencies]
arrow = { version = "^42.0", features = ["json", "prettyprint"] }
datatest-stable = { version = "0.1.3" }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96" }
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tempfile = "3"
test-case = { version = "3.1.0" }
tokio = { version = "1" }
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt",
] }

[[test]]
name = "dat_reader"
harness = false
